AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Config rules for AMI compliance monitoring'

Parameters:
  SecurityToolingAccountId:
    Type: String
    Description: Account ID where the compliance evaluator Lambda function is deployed
    AllowedPattern: '[0-9]{12}'
  
  ComplianceEvaluatorLambdaArn:
    Type: String
    Description: ARN of the compliance evaluator Lambda function
  
  ConfigDeliveryChannelName:
    Type: String
    Description: Name of the Config delivery channel
    Default: ami-lineage-config-channel
  
  ConfigBucketName:
    Type: String
    Description: S3 bucket name for Config delivery channel
    Default: ''
  
  ObjectLockRetentionDays:
    Type: Number
    Description: Number of days to retain objects with Object Lock (7 years = 2555 days)
    Default: 2555
    MinValue: 1
    MaxValue: 36500
  
  ObjectLockMode:
    Type: String
    Description: Object Lock retention mode (GOVERNANCE allows privileged users to override, COMPLIANCE cannot be overridden)
    Default: COMPLIANCE
    AllowedValues:
      - GOVERNANCE
      - COMPLIANCE

Resources:
  # Configuration Recorder
  ConfigurationRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: ami-lineage-config-recorder
      RoleARN: !GetAtt ConfigRole.Arn
      RecordingGroup:
        AllSupported: false
        IncludeGlobalResourceTypes: false
        ResourceTypes:
          - AWS::EC2::Image
          - AWS::EC2::Instance
          - AWS::AutoScaling::LaunchConfiguration
          - AWS::EC2::LaunchTemplate

  # Delivery Channel
  DeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      Name: !Ref ConfigDeliveryChannelName
      S3BucketName: !Ref ConfigBucket
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: Daily

  # S3 Bucket for Config
  ConfigBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "S3 access logging is not required for Config delivery bucket as CloudTrail provides sufficient audit trail for governance purposes"
      checkov:
        skip:
          - id: CKV_AWS_18
            comment: "S3 access logging is not required for Config delivery bucket as CloudTrail provides sufficient audit trail for governance purposes"
    Properties:
      BucketName: !Sub '${ConfigBucketName}-${AWS::AccountId}-${AWS::Region}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: !Ref ObjectLockMode
            Days: !Ref ObjectLockRetentionDays
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToInfrequentAccess
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: STANDARD_IA
              - TransitionInDays: 180
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
            NoncurrentVersionTransitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
      Tags:
        - Key: Purpose
          Value: AMI-Lineage-Compliance-Audit-Trail
        - Key: DataClassification
          Value: Confidential
        - Key: RetentionPolicy
          Value: 7-Years
        - Key: ObjectLockEnabled
          Value: 'true'

  # S3 Bucket Policy for Config
  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub '${ConfigBucket}'
            Condition:
              StringEquals:
                'AWS:SourceAccount': !Ref 'AWS::AccountId'
          - Sid: AWSConfigBucketExistenceCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:ListBucket
            Resource: !Sub '${ConfigBucket}'
            Condition:
              StringEquals:
                'AWS:SourceAccount': !Ref 'AWS::AccountId'
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${ConfigBucket}/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
                'AWS:SourceAccount': !Ref 'AWS::AccountId'

  # IAM Role for Config
  ConfigRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Explicit RoleName is required for organizational governance and cross-stack references"
    Properties:
      RoleName: AMI-Lineage-Config-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/ConfigRole
      Policies:
        - PolicyName: ConfigBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:ListBucket
                Resource: !Sub 'arn:aws:s3:::${ConfigBucket}'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${ConfigBucket}/*'
                Condition:
                  StringEquals:
                    's3:x-amz-acl': 'bucket-owner-full-control'
        - PolicyName: CrossAccountLambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref ComplianceEvaluatorLambdaArn
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref 'AWS::Region'

  # Config Rule: AMI Required Tags
  AMIRequiredTagsRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: ami-required-tags
      Description: Checks if AMIs have all required tags
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: REQUIRED_TAGS
      InputParameters: |
        {
          "requiredTagKeys": "Creator,Source,ApprovalStatus,SecurityScan,Environment"
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Image

  # Config Rule: AMI Approval Status
  AMIApprovalStatusRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: ami-approval-status
      Description: Checks if AMIs have approved status
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: !Ref ComplianceEvaluatorLambdaArn
      InputParameters: |
        {
          "rule": "approval_status"
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Image

  # Config Rule: AMI Security Scan Status
  AMISecurityScanRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: ami-security-scan-status
      Description: Checks if AMIs have passed security scans
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: !Ref ComplianceEvaluatorLambdaArn
      InputParameters: |
        {
          "rule": "security_scan_status"
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Image

  # Config Rule: AMI Naming Convention
  AMINamingConventionRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: ami-naming-convention
      Description: Checks if AMIs follow naming conventions
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: !Ref ComplianceEvaluatorLambdaArn
      InputParameters: |
        {
          "rule": "naming_convention"
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Image

  # Config Rule: AMI Lineage Verification
  AMILineageVerificationRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: ami-lineage-verification
      Description: Checks if AMIs have proper lineage information
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: !Ref ComplianceEvaluatorLambdaArn
      InputParameters: |
        {
          "rule": "lineage_verification"
        }
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Image

  # Config Rule: Instance AMI Compliance
  InstanceAMIComplianceRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: instance-ami-compliance
      Description: Checks if EC2 instances use compliant AMIs
      Source:
        Owner: AWS_CONFIG_RULE
        SourceIdentifier: !Ref ComplianceEvaluatorLambdaArn
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      InputParameters: |
        {
          "rule": "instance_ami_compliance"
        }

  # Config Rule: S3 Object Lock Enabled
  S3ObjectLockEnabledRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: s3-bucket-object-lock-enabled
      Description: Checks if S3 buckets storing AMI lineage and compliance data have Object Lock enabled
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket

  # Config Rule: S3 Bucket Versioning Enabled
  S3BucketVersioningRule:
    Type: AWS::Config::ConfigRule
    DependsOn: ConfigurationRecorder
    Properties:
      ConfigRuleName: s3-bucket-versioning-enabled
      Description: Checks if S3 buckets have versioning enabled (required for Object Lock)
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED
      Scope:
        ComplianceResourceTypes:
          - AWS::S3::Bucket

  # Remediation Configuration for AMI Approval
  AMIApprovalRemediation:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      ConfigRuleName: !Ref AMIApprovalStatusRule
      TargetType: SSM_DOCUMENT
      TargetId: AWSConfigRemediation-RemoveUnrestrictedSourceInSecurityGroup
      TargetVersion: '1'
      Parameters:
        AutomationAssumeRole:
          StaticValue: !GetAtt RemediationRole.Arn
      Automatic: false
      MaximumAutomaticAttempts: 3

  # IAM Role for Remediation
  RemediationRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "Explicit RoleName is required for organizational governance and cross-stack references"
          - id: W11
            reason: "EC2 describe and tag operations require wildcard permissions for Config rule remediation across all AMIs and instances"
    Properties:
      RoleName: AMI-Lineage-Remediation-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                'aws:RequestedRegion': !Ref 'AWS::Region'
      Policies:
        - PolicyName: RemediationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeImages
                  - ec2:DescribeInstances
                Resource: '*'
                Condition:
                  StringEquals:
                    'aws:RequestedRegion': !Ref 'AWS::Region'
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub 'arn:aws:sns:${AWS::Region}:${SecurityToolingAccountId}:ami-*'

  # CloudWatch Dashboard for Config Compliance
  ConfigComplianceDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: AMI-Compliance-Dashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Config", "ComplianceByConfigRule", "ConfigRuleName", "${AMIRequiredTagsRule}" ],
                  [ ".", ".", ".", "${AMIApprovalStatusRule}" ],
                  [ ".", ".", ".", "${AMISecurityScanRule}" ],
                  [ ".", ".", ".", "${AMINamingConventionRule}" ],
                  [ ".", ".", ".", "${AMILineageVerificationRule}" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "AMI Compliance Rules",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Config", "ComplianceByResourceType", "ResourceType", "AWS::EC2::Image" ],
                  [ ".", ".", ".", "AWS::EC2::Instance" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Compliance by Resource Type",
                "period": 300
              }
            }
          ]
        }

Outputs:
  ConfigurationRecorderName:
    Description: Name of the Config configuration recorder
    Value: !Ref ConfigurationRecorder
    Export:
      Name: !Sub '${AWS::StackName}-ConfigRecorderName'
  
  DeliveryChannelName:
    Description: Name of the Config delivery channel
    Value: !Ref DeliveryChannel
    Export:
      Name: !Sub '${AWS::StackName}-DeliveryChannelName'
  
  ConfigBucketName:
    Description: Name of the Config S3 bucket
    Value: !Ref ConfigBucket
    Export:
      Name: !Sub '${AWS::StackName}-ConfigBucketName'
  
  ConfigRoleArn:
    Description: ARN of the Config service role
    Value: !GetAtt ConfigRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ConfigRoleArn'
  
  DashboardURL:
    Description: URL of the CloudWatch dashboard
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ConfigComplianceDashboard}'
    Export:
      Name: !Sub '${AWS::StackName}-DashboardURL'
